### ISSUE TITLE
Oak overwrites the active colorscheme

### ISSUE THREAD

**Issue by bchopson** [vigoux/oak#5]
The latest commit 0859517d causes function definitions to be orange in python, even when oak is not set as the current colorscheme. Noted on neovim, vim, and gvim with `termguicolors` set. I have oak installed via vim-plug.

**Comment by bchopson** [comment]
Those `after/syntax` files might be getting loaded no matter what colorscheme is set...

**Comment by vigoux** [comment]
Oh, yes that sound like a mistake from my side, I'll add a check in those to assert we are actually using Oak !

**Comment by fladson** [comment]
Just confirming what @bchopson reported.
I spent some minutes debugging why some colors were off and finally found out it was the after hooks from oak.

**Comment by vigoux** [comment]
Hi, the error should be fixed since 9b90077685893701d4717667a7f0c5ce7982489c, could you confirm it is the case ?
Thnaks again for reporting.

**Comment by bchopson** [comment]
I can confirm the issue is resolved, thanks for fixing @vigoux!

**Comment by vigoux** [comment]
Sorry for taking so much time!
