### ISSUE TITLE
Listchars foreground color being the same as cursorline background color causes visibility issues

### ISSUE THREAD

**Issue by qookei** [vigoux/oak#6]
The listchars foreground color is the same as the cursorline background color, which means the listchars characters become invisible if the cursor is on a line with them, and so does the cursor when it's over them.

Example screenshot (cursor is over space between the `b`s):
![image](https://user-images.githubusercontent.com/50294583/206067086-9fa73188-ea89-4d0e-897f-4b2c4b50af28.png)

**Comment by qookei** [comment]
Looks like this is due to the trunk2 color change in #2 (as noted in the review)

**Comment by qookei** [comment]
Suggested fix: change the `Whitespace` color to trunk3:
![image](https://user-images.githubusercontent.com/50294583/206584408-712d9acb-957b-4bdd-8a3c-8ab021e8d577.png)

**Comment by vigoux** [comment]
Hi and sorry for the delay.
I would honestly keep the `ListChars` or `Whitespace` groups quite dim because they should not appear to disruptive.

You can, if you want, link the highlight groups to the appropriate colors though.

Sorry !
